### ISSUE TITLE
A question about Dataset Accessibility

### ISSUE THREAD

**Issue by XavierHeart** [tqwei05/PlantSeg#1]
Hi!
Thank you for your excellent work.It is truly impressive. I am currently trying to access the [dataset](https://zenodo.org/records/13293891) in [zenodo](https://zenodo.org/). But I can't download the data and it said "The record is publicly accessible, but files are restricted to users with access." Could you please let me know if the dataset is publicly accessible. Thanks a lot!
![图片](https://github.com/user-attachments/assets/bb38a95e-40a5-4be9-b8f7-77a88ef6bbd2)

**Comment by tqwei05** [comment]
Hello Xavier,

Thank you for your interest in our work. We will make this dataset publicly available in the near future.

**Comment by XavierHeart** [comment]
> Hello Xavier,
> 
> Thank you for your interest in our work. We will make this dataset publicly available in the near future.

Thank you for your response. I appreciate the update and will look forward to the public release of the dataset.

**Comment by tqwei05** [comment]
> > Hello Xavier,
> > Thank you for your interest in our work. We will make this dataset publicly available in the near future.
> 
> Thank you for your response. I appreciate the update and will look forward to the public release of the dataset.

The dataset is now available.
