### ISSUE TITLE
Not Found Healthy Plant Images

### ISSUE THREAD

**Issue by rae-shi** [tqwei05/PlantSeg#4]
Hi Tianqi Wei,

In this paper, _PlantSeg: A Large-Scale In-the-wild Dataset for Plant Disease Segmentation_, it says and i quote, 'PlantSeg is extensive, featuring 11,400 images with disease segmentation masks and an additional 8,000 healthy plant images categorized by plant type'. However, I couldn't find the healthy plant pictures in my downloaded dataset. Could you help me on this?

Thank you so much,

Rae

**Comment by tqwei05** [comment]
Hi Rae,

Healthy plant images are not included in the PlantSeg dataset. We will clarify this in the updated version of our paper.
