### ISSUE TITLE
Regarding F1 and mAcc in the paper

### ISSUE THREAD

**Issue by CN-fyl** [tqwei05/PlantSeg#5]
The baseline experimental results in the paper are labeled as mAcc, but the formula in the paper is not for mAcc; it's actually the formula for Mean Recall. Additionally, the mAcc in the paper is exactly the same as the F1 data on GitHub, so it might have been mislabeled.

**Comment by tqwei05** [comment]
Thank you for pointing out. We will address these in the revision of the paper.

**Comment by tqwei05** [comment]
The third column is mIoU, and the fourth column is mAcc.

**Comment by CN-fyl** [comment]
> The third column is mIoU, and the fourth column is mAcc.

Thank you for your reply. Wishing you success in your research!
